application:
  port: 8888
database:
  host: "localhost"
  port: 5433
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "http://localhost"
  sender_email: "mail@calumdev.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000
